"""Per-run cost computation for CC runs.

The CC SDK emits a final ``result`` event with a ``usage`` block:
``{"input_tokens", "output_tokens", "cache_creation_input_tokens",
"cache_read_input_tokens"}``. We persist those counts onto the Run row
and compute a USD estimate from a price set.

Prices change. The table here is the **last-resort** fallback (correct as
of ``PRICES_AS_OF``); live/cached prices live in ``domain/pricing.py`` and
are preferred at analytics-render time. ``scripts/update_prices.py`` can
refresh both the on-disk cache and this table. The UI surfaces the source
("live" / "cached" / "bundled") and its as-of date next to any cost so the
user knows it's an estimate.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping, Optional


PRICES_AS_OF = "2026-07-05"


# USD per 1M tokens. Model-id matching is prefix-based ("claude-opus-4"
# matches all opus-4 variants).
#
# Each row carries a "vendor" tag (defaulting to "anthropic" when absent, so
# rows regenerated by the script below without the tag still resolve
# correctly) used by the vendor-aware resolution in ``domain/pricing.py``.
# ``price_table()`` / ``compute_cost()`` stay vendor-agnostic on purpose: they
# are the last-resort, prefix-matched fallback used regardless of vendor.
#
# This list is the offline last-resort fallback. ``scripts/update_prices.py
# --regenerate`` rewrites the block between the @update-prices sentinels from a
# fetched price set (Anthropic rows only today; it does not emit a "vendor"
# key, which is fine -- the default covers it), and bumps ``PRICES_AS_OF`` to
# the fetch date. Keep the sentinels intact if you hand-edit.
# @update-prices begin
_PRICE_TABLE: list[tuple[str, dict[str, float]]] = [
    ("claude-opus-4", {
        "vendor": "anthropic",
        "input": 15.0, "output": 75.0,
        "cache_write": 18.75, "cache_read": 1.50,
    }),
    ("claude-sonnet-4", {
        "vendor": "anthropic",
        "input": 3.0, "output": 15.0,
        "cache_write": 3.75, "cache_read": 0.30,
    }),
    ("claude-haiku-4", {
        "vendor": "anthropic",
        "input": 1.0, "output": 5.0,
        "cache_write": 1.25, "cache_read": 0.10,
    }),
    # Older 3.x lines kept for back-compat with stale profiles.
    ("claude-3-opus", {
        "vendor": "anthropic",
        "input": 15.0, "output": 75.0,
        "cache_write": 18.75, "cache_read": 1.50,
    }),
    ("claude-3-5-sonnet", {
        "vendor": "anthropic",
        "input": 3.0, "output": 15.0,
        "cache_write": 3.75, "cache_read": 0.30,
    }),
    ("claude-3-5-haiku", {
        "vendor": "anthropic",
        "input": 1.0, "output": 5.0,
        "cache_write": 1.25, "cache_read": 0.10,
    }),
    # z.ai (docs.z.ai/guides/overview/pricing, checked 2026-07-05). Listed
    # most-specific prefix first so the vendor-agnostic prefix scan below
    # (which returns the first match, not the longest) picks "glm-5.2" /
    # "glm-5-code" over the bare "glm-5" for their own variants.
    # cache_write is seeded 0 while z.ai's "limited-time free" promo holds --
    # flip this to a real rate the day that promo ends.
    ("glm-5.2", {
        "vendor": "zai",
        "input": 1.40, "output": 4.40,
        "cache_read": 0.26, "cache_write": 0.0,
    }),
    ("glm-5.1", {
        "vendor": "zai",
        "input": 1.40, "output": 4.40,
        "cache_read": 0.26, "cache_write": 0.0,
    }),
    ("glm-5-code", {
        "vendor": "zai",
        "input": 1.20, "output": 5.00,
        "cache_read": 0.30, "cache_write": 0.0,
    }),
    ("glm-5", {
        "vendor": "zai",
        "input": 1.00, "output": 3.20,
        "cache_read": 0.20, "cache_write": 0.0,
    }),
]
# @update-prices end


def _without_vendor(prices: dict[str, float]) -> dict[str, float]:
    return {k: v for k, v in prices.items() if k != "vendor"}


def price_table() -> list[tuple[str, dict[str, float]]]:
    """The bundled fallback table (a stable copy; safe to mutate).

    Vendor-agnostic: the "vendor" tag is internal bookkeeping for
    :mod:`nightdesk.domain.pricing`'s vendor-aware resolution, stripped here
    so callers see only the four USD-per-1M rate fields, as before.
    """
    return [(prefix, _without_vendor(prices)) for prefix, prices in _PRICE_TABLE]


def bundled_prices_by_vendor(vendor: str) -> dict[str, dict[str, float]]:
    """Bundled entries for one vendor, keyed by prefix (vendor tag stripped).

    Rows with no explicit "vendor" tag are treated as "anthropic" (every row
    predating vendor tagging is a Claude row, and ``--regenerate`` still
    emits untagged rows). Used by :func:`nightdesk.domain.pricing.resolve_vendor_price`
    for the per-vendor bundled tier.
    """
    return {
        prefix: _without_vendor(prices)
        for prefix, prices in _PRICE_TABLE
        if prices.get("vendor", "anthropic") == vendor
    }


def bundled_prices_all() -> dict[str, dict[str, float]]:
    """Every bundled entry, keyed by prefix (vendor tag stripped), any vendor.

    Backs the "unknown vendor" best-effort fallback in
    :func:`nightdesk.domain.pricing.resolve_vendor_price`.
    """
    return {prefix: _without_vendor(prices) for prefix, prices in _PRICE_TABLE}


@dataclass
class RunUsage:
    model: Optional[str]
    input_tokens: int
    output_tokens: int
    cache_read_tokens: int
    cache_write_tokens: int
    cost_usd: Optional[float]


def _prices_for(model: Optional[str]) -> Optional[dict[str, float]]:
    if not model:
        return None
    for prefix, prices in _PRICE_TABLE:
        if model.startswith(prefix):
            return prices
    return None


def apply_prices(
    prices: dict[str, float],
    *,
    input_tokens: int,
    output_tokens: int,
    cache_read_tokens: int,
    cache_write_tokens: int,
) -> float:
    """USD cost from a per-1M-token price dict. The shared pricing primitive.

    Used by :func:`compute_cost` (bundled table) and by the live/cached
    repricing path in :mod:`nightdesk.domain.pricing` / analytics.
    """
    return (
        input_tokens * prices["input"]
        + output_tokens * prices["output"]
        + cache_read_tokens * prices["cache_read"]
        + cache_write_tokens * prices["cache_write"]
    ) / 1_000_000.0


def compute_cost(
    *,
    model: Optional[str],
    input_tokens: int,
    output_tokens: int,
    cache_read_tokens: int,
    cache_write_tokens: int,
) -> Optional[float]:
    """Return USD cost or None if the model is unknown.

    Uses the bundled ``_PRICE_TABLE`` (the last-resort fallback). This stays
    the per-run pricing primitive; analytics additionally reprices displayed
    totals from live/cached prices via :mod:`nightdesk.domain.pricing`.
    """
    prices = _prices_for(model)
    if prices is None:
        return None
    return apply_prices(
        prices,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        cache_read_tokens=cache_read_tokens,
        cache_write_tokens=cache_write_tokens,
    )


def extract_usage(result_event: dict[str, Any], *, model_hint: Optional[str] = None) -> RunUsage:
    """Pull usage counts out of a CC SDK ``result`` event.

    The SDK shape varies a little across versions; we read both the
    direct ``usage`` field and the nested ``message.usage`` form.
    Unknown fields default to 0.
    """
    usage = result_event.get("usage") or {}
    if not usage:
        msg = result_event.get("message") or {}
        usage = msg.get("usage") or {}
    model = result_event.get("model") or model_hint
    input_t = int(usage.get("input_tokens") or 0)
    output_t = int(usage.get("output_tokens") or 0)
    cache_read = int(
        usage.get("cache_read_input_tokens")
        or usage.get("cache_read_tokens")
        or 0
    )
    cache_write = int(
        usage.get("cache_creation_input_tokens")
        or usage.get("cache_write_tokens")
        or 0
    )
    cost = compute_cost(
        model=model,
        input_tokens=input_t,
        output_tokens=output_t,
        cache_read_tokens=cache_read,
        cache_write_tokens=cache_write,
    )
    return RunUsage(
        model=model,
        input_tokens=input_t,
        output_tokens=output_t,
        cache_read_tokens=cache_read,
        cache_write_tokens=cache_write,
        cost_usd=cost,
    )


def compute_cost_from_snapshot(
    usage_by_model: Mapping[str, Mapping[str, int]],
    snapshot: Mapping[str, Mapping[str, Any]],
) -> Optional[float]:
    """Sum USD cost across models from a run's stamped pricing snapshot.

    ``usage_by_model`` maps model id -> a plain dict of the four token counts
    (``input_tokens``, ``output_tokens``, ``cache_read_tokens``,
    ``cache_write_tokens``; missing keys default to 0). ``snapshot`` is the
    shape :func:`nightdesk.domain.pricing.build_pricing_snapshot` produces:
    model id -> {"input", "output", "cache_read", "cache_write", ...}.

    Mirrors :func:`compute_cost`'s None-propagation: a model with no usable
    rate (absent from the snapshot entirely, or present with null rates
    because resolution failed at run time) makes the whole result unknown
    rather than silently underselling the total by skipping it -- the same
    contract ``compute_cost`` gives for a single unknown model.
    """
    total = 0.0
    for model, usage in usage_by_model.items():
        entry = snapshot.get(model)
        if entry is None or entry.get("input") is None or entry.get("output") is None:
            return None
        prices = {
            "input": entry["input"],
            "output": entry["output"],
            "cache_read": entry.get("cache_read") or 0.0,
            "cache_write": entry.get("cache_write") or 0.0,
        }
        total += apply_prices(
            prices,
            input_tokens=int(usage.get("input_tokens") or 0),
            output_tokens=int(usage.get("output_tokens") or 0),
            cache_read_tokens=int(usage.get("cache_read_tokens") or 0),
            cache_write_tokens=int(usage.get("cache_write_tokens") or 0),
        )
    return total


def _has_rates(entry: Optional[Mapping[str, Any]]) -> bool:
    return entry is not None and entry.get("input") is not None and entry.get("output") is not None


def compute_cost_with_softened_fallback(
    usage_by_model: Mapping[str, Mapping[str, int]],
    snapshot: Mapping[str, Mapping[str, Any]],
    *,
    primary_model: Optional[str],
) -> tuple[Optional[float], list[str]]:
    """Sum USD cost across models, softening unpriceable secondary models to
    the primary model's rates instead of :func:`compute_cost_from_snapshot`'s
    strict None-propagation.

    For each model in ``usage_by_model``:

    - if ``snapshot`` has usable rates for it, price it directly;
    - else if ``primary_model`` differs from it and the snapshot has usable
      rates for ``primary_model``, price it at the primary's rates (recorded
      in the returned ``softened`` list);
    - else it is left out of the total entirely (no rate anywhere to use).

    Returns ``(None, [])`` only when *no* model could be priced at all --
    the caller should then keep whatever cost the harness itself reported,
    the same "unknown beats silently wrong" contract as
    ``compute_cost_from_snapshot``. Otherwise returns the summed cost of
    whichever models were priceable (directly or via fallback) plus the
    list of model ids that used the fallback. A model with neither its own
    rate nor a usable primary fallback is silently excluded from the sum
    (not an error -- callers that want to know can compare
    ``usage_by_model.keys()`` against what ended up in the snapshot).
    """
    primary_entry = snapshot.get(primary_model) if primary_model else None
    primary_has_rates = _has_rates(primary_entry)

    total = 0.0
    priced_any = False
    softened: list[str] = []
    for model, usage in usage_by_model.items():
        entry = snapshot.get(model)
        if _has_rates(entry):
            prices = entry
        elif primary_has_rates and model != primary_model:
            prices = primary_entry
            softened.append(model)
        else:
            continue
        total += apply_prices(
            {
                "input": prices["input"],
                "output": prices["output"],
                "cache_read": prices.get("cache_read") or 0.0,
                "cache_write": prices.get("cache_write") or 0.0,
            },
            input_tokens=int(usage.get("input_tokens") or 0),
            output_tokens=int(usage.get("output_tokens") or 0),
            cache_read_tokens=int(usage.get("cache_read_tokens") or 0),
            cache_write_tokens=int(usage.get("cache_write_tokens") or 0),
        )
        priced_any = True
    if not priced_any:
        return None, []
    return total, softened
