"""Per-run scoped tokens.

A run token is generated by the worker just before launching the sandbox
and injected into the sandboxed CC as ``NIGHTDESK_RUN_TOKEN``. The bearer
admin token is never put on a sandboxed run's environment; if the run
needs to call back into the API (spawn a child
ticket, etc.), it uses this scoped token instead.

The cleartext token never hits the DB — only its sha256 hash. On API
ingress, the request's bearer is hashed and looked up. Scopes determine
which routes/operations the token can perform.
"""
from __future__ import annotations

import hashlib
import secrets as secrets_mod
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Iterable, Optional

from sqlalchemy.orm import Session

from nightdesk.db.models import RunToken


# Self-scopes auto-granted to every run. Each is constrained to the run's
# own ticket; the ticket id is stored in scope_data and checked at ingress.
SELF_SCOPES: tuple[str, ...] = (
    "ticket.read.self",
    "ticket.update.next_run_context",
    "run.append_transcript.self",
    "run.mark_done.self",
)

# Scopes a profile may grant on top of the self-scopes.
GRANTABLE_SCOPES: tuple[str, ...] = (
    "ticket.create",
)

ALL_SCOPES: tuple[str, ...] = SELF_SCOPES + GRANTABLE_SCOPES


def _hash(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


@dataclass
class IssuedRunToken:
    cleartext: str
    token_hash: str
    expires_at: datetime
    scopes: list[str]


def issue_run_token(
    session: Session,
    *,
    run_id: str,
    ticket_id: str,
    extra_scopes: Iterable[str] = (),
    max_run_duration_seconds: int,
    grace_seconds: int,
    create_profile_allowlist: Optional[list[str]] = None,
) -> IssuedRunToken:
    """Generate, persist, and return a fresh run token."""
    cleartext = "ndr_" + secrets_mod.token_urlsafe(32)
    token_hash = _hash(cleartext)
    scopes = list(SELF_SCOPES)
    for s in extra_scopes:
        if s in GRANTABLE_SCOPES and s not in scopes:
            scopes.append(s)
    now = datetime.now(timezone.utc)
    expires_at = now + timedelta(seconds=max_run_duration_seconds + grace_seconds)
    scope_data: dict = {"ticket_id": ticket_id}
    if create_profile_allowlist:
        scope_data["create_profile_allowlist"] = list(create_profile_allowlist)
    row = RunToken(
        token_hash=token_hash,
        run_id=run_id,
        ticket_id=ticket_id,
        scopes=scopes,
        scope_data=scope_data,
        created_at=now,
        expires_at=expires_at,
    )
    session.add(row)
    session.commit()
    return IssuedRunToken(
        cleartext=cleartext, token_hash=token_hash,
        expires_at=expires_at, scopes=scopes,
    )


def revoke_run_token(session: Session, token_hash: str) -> None:
    row = session.get(RunToken, token_hash)
    if row is None or row.revoked_at is not None:
        return
    row.revoked_at = datetime.now(timezone.utc)
    session.commit()


def revoke_for_run(session: Session, run_id: str) -> None:
    from sqlalchemy import update

    now = datetime.now(timezone.utc)
    session.execute(
        update(RunToken)
        .where(RunToken.run_id == run_id, RunToken.revoked_at.is_(None))
        .values(revoked_at=now)
    )
    session.commit()


@dataclass
class RunPrincipal:
    """Resolved identity for a request authenticated by a run token."""
    token_hash: str
    run_id: str
    ticket_id: str
    scopes: tuple[str, ...]
    scope_data: dict


def resolve_run_token(session: Session, cleartext: str) -> Optional[RunPrincipal]:
    """Return the principal for a token if valid+unrevoked+unexpired, else None."""
    if not cleartext or not cleartext.startswith("ndr_"):
        return None
    row = session.get(RunToken, _hash(cleartext))
    if row is None:
        return None
    if row.revoked_at is not None:
        return None
    now = datetime.now(timezone.utc)
    expires_at = row.expires_at
    # SQLite drops tzinfo; assume stored timestamps are UTC.
    if expires_at.tzinfo is None:
        expires_at = expires_at.replace(tzinfo=timezone.utc)
    if expires_at <= now:
        return None
    return RunPrincipal(
        token_hash=row.token_hash,
        run_id=row.run_id,
        ticket_id=row.ticket_id,
        scopes=tuple(row.scopes or ()),
        scope_data=dict(row.scope_data or {}),
    )
